<script setup lang="ts">
/**
 * Primary responsibility: displays the Rota in a responsive grid.
 * Refactored to eliminate nested templates and resolve TypeScript type errors.
 */
import { computed, h } from 'vue';

import BaseTable from '@/components/shared/BaseTable.vue';
import { useRotaColors } from '@/features/rota/composables/useRotaColors';

import RotaSlot from './RotaSlot.vue';

/**
 */

/**
 * role - The role object.
 * role.id - Role ID.
 * role.name - Role name.
 * surgery - The surgery object.
 * surgery.id - Surgery ID.
 * surgery.name - Surgery name.
 * [_isGroupStart] - Generated by BaseTable.
 */

const props = defineProps({
  days: { type: Array, required: true },
  rows: { type: Array, required: true },
  getShifts: { type: Function, required: true }
});

const emit = defineEmits(['slot-click']);

const { getRoleColor } = useRotaColors();

// --- Helpers ---

/**
 * Converts a string to sentence case.
 * @param str - The input string.
 * @returns Formatted string.
 */
const toSentenceCase = (str) => {
  if (!str) return '';
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
};

/**
 * Generates style object for role badges.
 * @param roleId - The ID of the role.
 * @returns Style object.
 */
const getRoleBadgeStyle = (roleId) => {
  const c = getRoleColor(roleId);
  return {
    backgroundColor: c.bg,
    color: c.accent,
    borderColor: c.accent
  };
};

// --- Custom Cell Components ---

/**
 * Component for the Role and Surgery header column.
 * @param cellProps - Component props.
 * @param cellProps.item - The row data item.
 * @returns Virtual node for rendering.
 */
const RoleSurgeryCell = (cellProps) => {
  const item = cellProps.item;

  return h('div', { class: 'header-col-inner' }, [
    item._isGroupStart
      ? h(
          'div',
          {
            class: 'role-title',
            style: getRoleBadgeStyle(item.role.id)
          },
          toSentenceCase(item.role.name)
        )
      : null,
    h('div', { class: 'surgery-subtitle' }, item.surgery.name)
  ]);
};

/**
 * Component for the empty table state.
 * @returns Virtual node for rendering.
 */
const EmptyState = () =>
  h('div', { class: 'empty-state-content' }, [
    h('p', 'No roles configured. Please add Roles and Surgeries.')
  ]);

// --- Table Configuration ---

const tableHeaders = computed(() => {
  // Double-cast to break 'unknown[]' inference from props
  const days = props.days;

  return [
    {
      key: 'header_col',
      label: 'Role / Surgery',
      width: 'minmax(0, 9.2rem)',
      align: 'left',
      component: RoleSurgeryCell,
      props: (item) => ({ item })
    },
    ...days.map((d) => ({
      key: d.key,
      label: d.label,
      width: 'minmax(0, 1fr)',
      align: 'left',
      headerClass: d.isToday ? 'header-today' : '',
      component: RotaSlot,
      props: (item) => ({
        isBeforeToday: d.isBeforeToday,
        isToday: d.isToday,
        isWeekend: d.isWeekend,
        roleId: item.role.id,
        shifts: props.getShifts(item.role.id, item.surgery.id, d.iso)
      }),
      listeners: (item) => ({
        click: () => emit('slot-click', { rowItem: item, day: d })
      })
    }))
  ];
});
</script>

<template>
  <BaseTable
    class="rota-table"
    :empty-component="EmptyState"
    group-by="role.id"
    :headers="tableHeaders"
    :items="props.rows"
    :vertical-lines="true"
  />
</template>

<style scoped>
/* Header Column Styling */
:deep(.header-col-inner) {
  display: flex;
  flex-direction: column;
  height: 100%;
  justify-content: center;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  width: 100%;
}

:deep(.role-title) {
  align-self: flex-start;
  border: 1px solid transparent;
  border-radius: 4px;
  display: inline-block;
  font-size: 0.75rem;
  font-weight: 700;
  letter-spacing: 0.05em;
  margin-bottom: 0.25rem;
  max-width: 100%;
  overflow: hidden;
  padding: 2px 6px;
  text-overflow: ellipsis;
  white-space: nowrap;
}

:deep(.surgery-subtitle) {
  color: var(--text-muted);
  font-size: 0.85rem;
  overflow: hidden;
  padding-left: 4px;
  text-overflow: ellipsis;
  white-space: nowrap;
}

/* Header Highlight for Today */
:deep(th.header-today),
:deep(.header-cell.header-today) {
  background-color: #eff6ff !important;
  color: #2563eb !important;
  font-weight: 800 !important;
}

.empty-state-content {
  color: var(--text-muted);
  padding: 5rem;
  text-align: center;
}
</style>
